# Generated by Django 4.2.5 on 2025-10-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='user',
            new_name='users',
        ),
    ]
