# Generated by Django 4.2.5 on 2025-10-25 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_rename_user_membership_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-created_at'], 'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='users',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='join_date',
        ),
        migrations.AddField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='basic', max_length=20),
        ),
    ]
